### PR TITLE
Revert recent changes

### PR DESCRIPTION
**Pull request by nmrugg**
It turned out that also #32 caused another issue with the advanced demo as well. So, I'm revering that too.

Maybe we can set something  up with BrowserStack. They have free open source plans.

### CODE REVIEW

**Comment by addaleax** [comment]
Sure, feel free to look into that – My experience with Travis CI + Karma was pretty good so far for browser testing, but if covering a variety of different browsers and versions is important, that sounds like a good idea.

**Comment by nmrugg** [comment]
I like the recent changes, we just need to find a way to merge them without casing issues or bump the major version and modify the demos.

I know there are some major users who want to support a lot of browsers, but we should try to make it work as fast as possible on newer browsers. I will try to setup something with BrowserStack.

**Comment by addaleax** [comment]
Well yeah, I definitely know why the advanced demo had some trouble – I’ll write a fix for that in the v3 branch. And I think if we want to be lazy, we could just include some very basic polyfill for Uint8Array (essentially a zero-initializing Array wrapper would suffice); that wouldn’t be more than two or three lines I guess.

**Comment by nmrugg** [comment]
I like lazy.

**Comment by addaleax** [comment]
Okay, sorry, that seems a bit harder than first thought – it’s not that easy to get that
```js
arr[10] = 300;
=> arr[10] == 44
```
behaviour that Uint8Arrays have. If we want, we could extract this one type of array from [here](https://github.com/substack/typedarray) for example, but maybe it would be better to just leave that up to the user…

**Comment by nmrugg** [comment]
Yeah, that's what the  `& 255` fixes. Is it much slower keeping those in?

**Comment by addaleax** [comment]
Well, I imagine it’s the main thing that makes encoding/decoding faster when using Uint8Arrays (plus possibly some advantage from having a smaller memory footprint)… I guess I can try to take apart fa25f549137c8d408 and see how much of a difference it makes, but not today.

**Comment by nmrugg** [comment]
Sounds great. Or maybe we can fix the array afterward if needed?

**Comment by addaleax** [comment]
The `& 255` and `>> 24 << 24` bits actually don’t seem to make *that* much of a difference (possibly about 5 %, but it’s hard to tell since I couldn’t fully take fa25f54 to create a working version that uses typed arrays but leaves those casts in place), at least on Node.js, so I guess the better memory management is the more important part here.

I have thought about it a bit though, and maybe just continuing to maintain the 2.x line for users which decide not to want polyfills is the simplest and most feasible solution?

**Comment by nmrugg** [comment]
That might be the best approach. I'll think about it.

**Comment by jakirkham** [comment]
Could you just add new functions for these features for now? Would be really great to work only with`Uint8Array`s.

**Pull request merged**
