### PR TITLE
Use the TextEncoder/TextDecoder or Buffer API if available

### PR DESCRIPTION
**Pull request by addaleax**
Recent browsers (Chrome, FF, Opera) provide an API (https://encoding.spec.whatwg.org/#api) for encoding/decoding strings, and Node.js provides `new Buffer()`, both of which are notably faster than a purely JS-based approach, so use these if available.

### CODE REVIEW

**Comment by addaleax** [comment]
@nmrugg ping?

**Comment by nmrugg** [comment]
Yeah, sorry, I've been busy. I checked out the code pretty thoroughly though, and it looks good. I'll try to tackle these PRs soon.

**Comment by nmrugg** [comment]
I'll try to work on this over the weekend.

Sorry, I've been so slow. So much stuff going on.

Maybe I should setup a github organization for LZMA-JS and you could join that.

**Comment by addaleax** [comment]
No problem, we all have other things to do besides maintaining cool OSS :)
Feel free setup a org (or add me as a collaborator here), and I’ll be glad to help where I can, but right now I don’t have any plans for more improvements here from my side :)

**Pull request merged**
