### PR TITLE
Decrease String.fromCharCode.apply parameter length to 16K

### PR DESCRIPTION
**Pull request by addaleax**
According to [Chromium issue 252492](https://code.google.com/p/chromium/issues/detail?id=252492), the argument count limit for .apply in Web Workers is not 64 KiB as for regular non-Web Worker scripts. Due to this, decompression of files with an uncompressed length of at least 64 KiB and more fails with `RangeError: Maximum call stack size exceeded` when using Chromium Web Workers.
A suggested workaround there is to use blocks of 16 KiB instead, which this patch implements.

Commit which introduced the bug: 15a539bd5e6c00d85a726640e95f9e7a136c1cd5
cc @nhaesler

### CODE REVIEW

**Comment by nmrugg** [comment]
Good find. Thanks for the pull request.

I can't  believe they haven't fixed this bug in Chrome.

**Comment by addaleax** [comment]
Yeah, I don’t know whether this behaviour is intentional, since nobody from the Chromium team seems to have said something about that there.
Anyway, thanks for including this! Could you publish a new version with this soon?

**Comment by nmrugg** [comment]
Yes. I was just doing a little investigation into benchmarking. But I 
suppose there's no rush, so I'll push a new version first.

**Comment by addaleax** [comment]
Ah, sure, do that first if you want; I ran the test script before and after my changes, and it was actually about 3 % faster with the smaller size (But, of course, I don’t think my one-time all-tests run should be considered too significant)

**Comment by nmrugg** [comment]
My results are essentially the same. Win-win. Thanks again.

**Pull request merged**
