### PR TITLE
Revert typed array code

### PR DESCRIPTION
**Pull request by nmrugg**
Seeing if this will pass build.

### CODE REVIEW

**Comment by addaleax** [comment]
The `TextEncoder`/`TextDecoder` change should not really have any influence on Node.js. But yes, feel free to merge this when it passes, I’ll set up the v3 branch then.

**Comment by nmrugg** [comment]
I thought so too, and Travis <a href=https://travis-ci.org/nmrugg/LZMA-JS/builds/119009609>agrees</a>. I was just curious.

I agree that we don't need to support 0.8 any more, but I am also wondering about the browser support. I don't know all of the browsers we should (or do) support. In the past, I think it's been pretty robust. I tested earlier versions on IE6 (mainly just for fun). It would be nice to keep wide support unless there is a good reason to drop old browsers (which there might be).

**Comment by nmrugg** [comment]
Oh, and I also noticed that the <a href=http://nmrugg.github.io/LZMA-JS/demos/advanced_demo.html>advanced demo</a> is having problems.

**Comment by addaleax** [comment]
I guess that must be #39 – revert that one, too, then.

**Comment by nmrugg** [comment]
Yeah, I think you're right.

**Pull request merged**
