### PR TITLE
Docs for #39

### PR DESCRIPTION
**Pull request by addaleax**
Add docs for the `is_utf8` parameter introduced in #39. I also replaced some of the HTML in the `readme.md` with markdown primitives, but of course you can leave that out if you want.

### CODE REVIEW

**Comment by nmrugg** [comment]
:+1:

Looks good. I added you as a contributor, so now you should be able to push and merge. Do you want to try merging this?

**Comment by addaleax** [comment]
Thanks! :) If you want to add me for npm (and that’s completely up to you), I’m `sqrt` over there.

**Comment by nmrugg** [comment]
I'll think about it.

Do you want to create a v3 branch with the other changes you had made? I think they are good, but since there's a lot of changes, I'd like to make sure we have it thoroughly tested first.

**Comment by addaleax** [comment]
Mh, that would probably have been a good idea, but since you already merged #28 (and the others, but mostly that one) into master, I’m not sure how exactly that branch (except maybe the version number in the package.json) would be different from the current head?

**Comment by nmrugg** [comment]
Yeah...I just realized that. I most have forgotten. Well, I think it's working well, so it shouldn't be a problem. Let's just keep master passing.

**Comment by addaleax** [comment]
Other than that, I guess I have some time in the next days to see if I can add some automated browser testing to the CI (already did that for [object-hash](https://github.com/puleos/object-hash)). 

And btw, I’ve been using those changes in a production environment for a while now, with no problems whatsoever.

**Comment by nmrugg** [comment]
Or maybe not... Travis is <a href=https://travis-ci.org/nmrugg/LZMA-JS/builds/119003645>complaining</a> about node 0.8 not working. I must not have minfied the merged code earlier. I think I will try to revert and then make a new branch.

**Comment by nmrugg** [comment]
Or is 0.8 too old to care about?

**Comment by addaleax** [comment]
0.10 came out 2013-03-11, and I don’t think any OS ships an earlier version anymore. And yes, I haven’t seen any modules explicitly supporting < 0.10 for months now, so that should be fine.

**Pull request merged**
